# Generated by Django 4.1.3 on 2022-12-01 07:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="places",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                null=True, srid=4326, verbose_name="Место"
            ),
        ),
    ]
