# Generated by Django 4.1.3 on 2022-11-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
