# Generated by Django 4.1.3 on 2022-12-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_places_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="places",
            name="desctiption",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
